<?php
$config = array(
	'name' => 'kumo',
	'version' => '1.0.0',
	'thumbnail' => 'img/thumbnail.png',
	'style_file' => 'css/docs.css',
	'templates' => array(
		'top' => array(
			'filename' => 'top.skin.php',
			'layouts' => array('SiteNavigator', 'SiteFooter'),
			'thumbnail' => 'img/thumbnail.top.png',
		),
	),
	'default_template' => 'top',
	'eyecatch'   => array(
		'wrap' => 'eyecatch.wrap.php',
		'item' => 'eyecatch.item.php',
	),
	'colors' => array(
		'black'          => 'css/color.black.css',
		'brown'          => 'css/color.brown.css',
		'turquoise'      => 'css/color.turquoise.css',
		'ruby'           => 'css/color.ruby.css',
		'lapis'          => 'css/color.lapis.css',
		'green'          => 'css/color.green.css',
		'wakatake'       => 'css/color.wakatake.css',
		'seiji'          => 'css/color.seiji.css',
		'haizakura'      => 'css/color.haizakura.css',
		'shinbashi'      => 'css/color.shinbashi.css',
		'mizu'           => 'css/color.mizu.css',
		'gold'           => 'css/color.gold.css',
		'grayshblue'     => 'css/color.grayshblue.css',
		'grayshgreen'    => 'css/color.grayshgreen.css',
		'shironeri'      => 'css/color.shironeri.css',
		'white'          => 'css/color.white.css',
		'white-orange'   => 'css/color.white-orange.css',
		'white-green'    => 'css/color.white-green.css',
		'white-amethyst' => 'css/color.white-amethyst.css',
	),
	'textures' => array(
		'hemp'        => 'css/texture.hemp.css',
		'arches'      => 'css/texture.arches.css',
		'struckaxiom' => 'css/texture.struckaxiom.css',
		'swirl'       => 'css/texture.swirl.css',
		'greytile'    => 'css/texture.greytile.css',
		'ravenna'     => 'css/texture.ravenna.css',
		'wood'        => 'css/texture.wood.css',
		'wood2'       => 'css/texture.wood2.css',
		'grass'       => 'css/texture.grass.css',
		'sea'         => 'css/texture.sea.css',
		'aurora'      => 'css/texture.aurora.css',
		'cloth'       => 'css/texture.cloth.css',
		'paper'       => 'css/texture.paper.css',
		'custom'      => 'css/texture.custom.css',
	),
	'sample_style_file' => 'css/samples.css',
);
